version: '3.8'

services:
  superset:
      build:
        context: ./superset
      container_name: superset
      environment:
        - ADMIN_USERNAME=admin
        - ADMIN_EMAIL=admin@superset.com
        - ADMIN_PASSWORD=admin
      ports:
        - '8088:8088'
  trino-coordinator:
    image: trinodb/trino:latest
    ports:
      - "8080:8080" 
    hostname: trino-coordinator
    volumes:
      - ./etc:/etc/trino
      - ./conf:/etc/trino/conf


  minio:
    hostname: minio
    image: 'minio/minio:latest'
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address ":9001"

  postgres:
    image: 'postgres'
    hostname: postgres
    expose:
      - '5432'
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hive_db

  hive-metastore:
    hostname: hive-metastore
    build: .
    ports:
      - '9083:9083' # Port of metastore
    volumes:
      - ./conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml
      - ./conf/core-site.xml:/opt/hadoop-3.4.0/etc/hadoop/core-site.xml
    environment:
      METASTORE_DB_HOSTNAME: postgres
      METASTORE_TYPE: postgres
    depends_on:
      - postgres

volumes:
  minio-data:
    driver: local
